language: python

cache: pip

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      addons:
        apt:
          packages:
          - chromium-browser
          - chromium-chromedriver
      before_install:
        - python3 -m pip install --upgrade pip

    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - choco install googlechrome
        - choco install chromedriver
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      addons:
        chrome: stable
        
branches:
  only:
    - master

install:
  - pip3 install -r requirements.txt    # install dependencies

# command to run tests
script:
  - python -m unittest test || python3 -m unittest test.py
